name: aura_care
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pretty_gauge: ^1.0.1
  swipeable_button_view: ^0.0.2
  page_transition: ^2.2.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/auraCareMainLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
